app/views/authorization.py
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
from flask import Blueprint, flash, make_response, request, redirect
from flask import render_template, url_for
from flask import session as login_session
from oauth2client.client import flow_from_clientsecrets
from oauth2client.client import FlowExchangeError
import user as user
import httplib2
import json
import requests
import random
import string

auth = Blueprint('auth', __name__)

GOOGLE_CLIENT_SECRET = "client_secret.json"
GOOGLE_CLIENT_ID = json.loads(
    open(GOOGLE_CLIENT_SECRET, "r").read())["web"]["client_id"]


@auth.route("/login")
def show_login():
    """Create anti-forgery state token."""
    state = "".join(random.choice(string.ascii_uppercase + string.digits)
                    for x in range(32))
    login_session["state"] = state
    return render_template("login.html", STATE=state)


@auth.route("/gconnect", methods=["POST"])
def gconnect():
    """Google connect."""

    # Validate state token
    if request.args.get("state") != login_session["state"]:
        response = make_response(json.dumps("Invalid state parameter."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Obtain authorization code
    code = request.data

    try:
        # Upgrade the authorization code into a credentials object
        oauth_flow = flow_from_clientsecrets(GOOGLE_CLIENT_SECRET, scope="")
        oauth_flow.redirect_uri = "postmessage"
        credentials = oauth_flow.step2_exchange(code)
    except FlowExchangeError:
        response = make_response(
            json.dumps("Failed to upgrade the authorization code."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Check that the access token is valid.
    access_token = credentials.access_token
    url = ("https://www.googleapis.com/oauth2/v1/tokeninfo?"
           "access_token={}").format(access_token)
    h = httplib2.Http()
    result = json.loads(h.request(url, "GET")[1])

    # If there was an error in the access token info, abort.
    if result.get("error") is not None:
        response = make_response(json.dumps(result.get("error")), 500)
        response.headers["Content-Type"] = "application/json"
        return response

    # Verify that the access token is used for the intended user.
    gplus_id = credentials.id_token["sub"]
    if result["user_id"] != gplus_id:
        response = make_response(
            json.dumps("Token's user ID doesn't match given user ID."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Verify that the access token is valid for this app.
    if result["issued_to"] != GOOGLE_CLIENT_ID:
        response = make_response(
            json.dumps("Token's client ID does not match app's."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    stored_access_token = login_session.get("access_token")
    stored_gplus_id = login_session.get("gplus_id")
    if stored_access_token is not None and gplus_id == stored_gplus_id:
        response = make_response(
            json.dumps("Current user is already connected."), 200)
        response.headers["Content-Type"] = "application/json"
        return response

    # Store the access token in the session for later use.
    login_session["access_token"] = credentials.access_token
    login_session["gplus_id"] = gplus_id

    # Get user info
    userinfo_url = "https://www.googleapis.com/oauth2/v1/userinfo"
    params = {"access_token": credentials.access_token, "alt": "json"}
    answer = requests.get(userinfo_url, params=params)

    data = answer.json()

    login_session["username"] = data["name"]
    login_session["picture"] = data["picture"]
    login_session["email"] = data["email"]

    # Add provider to login session.
    login_session["provider"] = "google"

    # See if user exists, if it doesn't make a new one.
    user_id = user.get_user_id(data["email"])
    if not user_id:
        user_id = user.create_user(login_session)
    login_session["user_id"] = user_id

    output = "<h1>Welcome, "
    output += login_session["username"]
    output += "!</h1>"
    output += '<img src="' + login_session["picture"] + '" '
    output += 'style = "width: 300px; height: 300px; border-radius: 150px; '
    output += '-webkit-border-radius: 150px; -moz-border-radius: 150px;"> '
    flash(
        "You are now logged in as {}.".format(login_session["username"]),
        "success")
    return output


@auth.route("/gdisconnect")
def gdisconnect():
    """Google disconnect."""
    # Revoke a current user's token and reset their login_session.
    # Only disconnect a connected user.
    access_token = login_session.get("access_token")
    if access_token is None:
        response = make_response(
            json.dumps("Current user not connected."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    url = "https://accounts.google.com/o/oauth2/revoke?token={}".format(
            access_token)
    h = httplib2.Http()
    result = h.request(url, "GET")[0]

    if result["status"] == "200":
        del login_session["access_token"]
        del login_session["gplus_id"]
        del login_session["username"]
        del login_session["email"]
        del login_session["picture"]
        response = make_response(json.dumps("Successfully disconnected."), 200)
        response.headers["Content-Type"] = "application/json"
        return response
    else:
        response = make_response(
            json.dumps("Failed to revoke token for given user.", 400))
        response.headers["Content-Type"] = "application/json"
        return response


@auth.route("/fbconnect", methods=["POST"])
def fbconnect():
    """Facebook connect."""
    if request.args.get("state") != login_session["state"]:
        response = make_response(json.dumps("Invalid state parameter."), 401)
        response.headers["Content-Type"] = "application/json"
        return response

    # Access token received (see access_token).
    access_token = request.data

    app_id = json.loads(open("fb_client_secrets.json", "r")
                        .read())["web"]["app_id"]
    app_secret = json.loads(
        open("fb_client_secrets.json", "r").read())["web"]["app_secret"]

    url = ("https://graph.facebook.com/oauth/access_token?"
           "grant_type=fb_exchange_token&client_id={}&client_secret={}"
           "&fb_exchange_token={}").format(app_id, app_secret, access_token)
    h = httplib2.Http()
    result = h.request(url, "GET")[1]

    # Use token to get user info from API.
    # userinfo_url = "https://graph.facebook.com/v2.8/me"
    """
    Due to the formatting for the result from the server token exchange we
    have to split the token first on commas and select the first index which
    gives us the key : value for the server access token then we split it on
    colons to pull out the actual token value and replace the remaining quotes
    with nothing so that it can be used directly in the graph api calls
    """
    token = result.split(",")[0].split(":")[1].replace('"', "")

    url = ("https://graph.facebook.com/v2.8/me?"
           "access_token={}&fields=name,id,email").format(token)
    h = httplib2.Http()
    result = h.request(url, "GET")[1]
    data = json.loads(result)
    login_session["provider"] = "facebook"
    login_session["username"] = data["name"]
    login_session["email"] = data["email"]
    login_session["facebook_id"] = data["id"]

    # The token must be stored in the login_session in order to properly
    # logout.
    login_session["access_token"] = token

    # Get user picture.
    url = ("https://graph.facebook.com/v2.8/me/picture?"
           "access_token={}&redirect=0&height=200&width=200").format(token)
    h = httplib2.Http()
    result = h.request(url, "GET")[1]
    data = json.loads(result)

    # See if user exists.
    user_id = user.get_user_id(login_session["email"])
    if not user_id:
        user_id = user.create_user(login_session)
    login_session["user_id"] = user_id

    output = "<h1>Welcome, "
    output += login_session["username"]
    flash("Now logged in as {}.".format(login_session["username"]), "success")
    return output


@auth.route("/fbdisconnect")
def fbdisconnect():
    """Facebook disconnect."""
    facebook_id = login_session["facebook_id"]

    # The access token must be included to successfully logout.
    access_token = login_session["access_token"]
    url = "https://graph.facebook.com/{}/permissions?access_token={}".format(
            facebook_id, access_token)
    h = httplib2.Http()
    h.request(url, "DELETE")[1]
    return "You have been logged out."


@auth.route("/disconnect")
def disconnect():
    """Disconnect based on provider."""
    login_session["provider"] = "google"

    if "provider" in login_session:
        if login_session["provider"] == "google":
            gdisconnect()
            delete_key_login_session("gplus_id")
            delete_key_login_session("credentials")

        if login_session["provider"] == "facebook":
            fbdisconnect()
            del login_session["facebook_id"]

        delete_key_login_session("username")
        delete_key_login_session("email")
        delete_key_login_session("user_id")
        delete_key_login_session("provider")
        flash("You have successfully been logged out.", "success")
        return redirect(url_for("category.show_categories"))
    else:
        flash("You were not logged in.", "success")
        return redirect(url_for("category.show_categories"))


def delete_key_login_session(key):
    try:
        del login_session[key]
    except:
        return

app/views/category.py
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
from flask import Blueprint, render_template
from sqlalchemy import asc, desc
from app.models.models import Category
from app.models.models import Item
from app import session

category = Blueprint('category', __name__)

@category.route("/")
@category.route("/catalog")
def show_categories():
    """Show Categories on homescreen."""
    categories = session.query(Category).order_by(asc(Category.name)).all()
    return render_template('categories.html', categories=categories)

app/views/item.py
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
from flask import Blueprint, render_template, request, redirect, flash, url_for
from flask import session as login_session
from sqlalchemy import asc, desc, exc
from app.models.models import Category
from app.models.models import Item
from app import session
from functools import wraps

item = Blueprint('item', __name__)


def login_required(f):
    """Decorator to redirect user if not logged."""
    @wraps(f)
    def wrapper(*args, **kwds):
        if "username" not in login_session:
            return redirect("/login")
        return f(*args, **kwds)
    return wrapper


def owner_permission(f):
    """Decorator to make sure the user owns an item
       before allowing them to edit or delete it.
    """
    @wraps(f)
    def wrapper(*args, **kwds):
        category_name = kwds["category_name"]
        item_style = kwds["item_style"]

        # Redirect user if category or item does not exist.
        category = session.query(Category).filter_by(
            name=category_name).one_or_none()
        if not category:
            flash("An error occurred. Please try again.", "warning")
            return redirect("/catalog")

        item = session.query(Item).filter_by(
            category_id=category.id, style=item_style).one_or_none()
        if not item:
            flash("An error occurred. Please try again.", "warning")
            return redirect("/catalog/{}/items".format(category_name))

        # Make sure the user owns an item before allowing them to edit
        # or delete it.
        if "username" not in login_session\
                or "user_id" in login_session\
                and item.user_id != login_session["user_id"]:
            flash("You are not the owner of this item. "
                  "You do not have permission to edit/delete.")
            return redirect("/catalog/{}/items".format(category_name))

        kwds['item_style'] = item_style
        return f(*args, **kwds)
    return wrapper


@item.route("/catalog/<path:category_name>")
@item.route("/catalog/<path:category_name>/items")
def show_items(category_name):
    """Show a category and all of his items."""
    categories = session.query(Category).order_by(asc(Category.name)).all()
    category = session.query(Category).filter_by(
        name=category_name).one_or_none()
    items = session.query(Item).filter_by(category=category).all()
    return render_template(
        'show_item.html', categories=categories,
        category=category, items=items)


@item.route("/catalog/<path:category_name>/<path:item_style>")
def show_item(category_name, item_style):
    """Show a category and specific item."""
    category = session.query(
        Category).filter_by(name=category_name).one_or_none()
    item = session.query(Item).filter_by(
        category=category, style=item_style).one_or_none()
    return render_template('item_detail.html', category=category, item=item)


@item.route('/catalog/<path:category_name>/items/new', methods=['GET', 'POST'])
@login_required
def new_item(category_name):
    '''
    GET: Display Add Form
    POST: Create New Item
    '''
    category = session.query(
        Category).filter_by(name=category_name).one_or_none()

    if request.method == 'POST':
        newItem = Item()
        if request.form['style']:
            style = request.form['style'].strip()
        if request.form['description']:
            description = request.form['description'].strip()
        try:
            newItem = Item(
                style=style, description=description,
                category=category, user_id=login_session['user_id'])
        except UnboundLocalError:
            session.rollback()
            flash("You can not add an item without "
                  " a name and/or description.")
            return redirect(
                url_for("item.new_item", category_name=category.name))
        try:
            item = session.query(Item).filter_by(
                category=category, style=style).one_or_none()
            session.add(newItem)
            session.commit()
            flash("Item '{}' Successfully Added".format(
                newItem.style), "success")
            return redirect('/catalog')
        except exc.SQLAlchemyError:
            session.rollback()
            flash(
                "You can not add this item since another item already "
                " exists in the database with the same"
                " style and category.")
            return redirect(
                url_for("item.new_item", category_name=category.name))
    else:
        return render_template('new_item.html', category=category)


@item.route(
    '/catalog/<path:category_name>/<path:item_style>/edit',
    methods=['GET', 'POST'])
@login_required
@owner_permission
def edit_item(category_name, item_style):
    category = session.query(
        Category).filter_by(name=category_name).one_or_none()
    item = session.query(Item).filter_by(style=item_style).one_or_none()
    if request.method == 'POST':
        if request.form['style']:
            item.style = request.form['style'].strip()
        if request.form['description']:
            item.description = request.form['description'].strip()
        session.add(item)
        session.commit()
        flash("Item '{}' Successfully Edited".format(item.style), "success")
        return redirect('/catalog')
    else:
        return render_template('edit_item.html', category=category, item=item)


@item.route(
    '/catalog/<path:category_name>/<path:item_style>/delete',
    methods=['GET', 'POST'])
@login_required
@owner_permission
def delete_item(category_name, item_style):
    category = session.query(
        Category).filter_by(name=category_name).one_or_none()
    item = session.query(Item).filter_by(style=item_style).one_or_none()
    if request.method == 'POST':
        session.delete(item)
        session.commit()
        return redirect('/catalog')
    else:
        return render_template(
            'delete_item.html', category=category, item=item)

app/templates/categories.html
{% extends "index.html" %}
{% block content %}
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
    <section class="container">
        <h3 class = 'cat-head'>Categories</h3>
        {% if categories %}
            <div class="row">
                {% for c in categories %}
                    <button class="col-sm-4">
                      <a class= cat-link href ="{{url_for('item.show_items', category_name=c.name)}}">{{c.name}}</a>
                    </button>

                {% endfor %}
            </div>
        {% endif %}
{% endblock %}

app/templates/delete_item.html
{% block content %}
{% include "partials/navbar.html" %}

<div class="container">
	<div class="row">
		<div class="col-md-12">
            <h1>Delete Item</h1>
                <h2>Do you really want to delete {{item.style}}?</h2>
                <form class= "delete-cancel" action="#" method = 'post'>
                        <button type="submit" class="btn btn-info" id="submit" type="submit">
                        <span aria-hidden="true"></span>Delete</button>
                        <a href = "{{url_for('item.show_item', category_name=category.name, item_style=item.style)}}">
                            <button class="btn btn-info">
                            <span aria-hidden="true"></span> Cancel</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

app/templates/edit_item.html
{% block content %}
{% include "partials/navbar.html" %}

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2>Edit Item</h2>
			{% with messages = get_flashed_messages() %}
			{% if messages %}
			  {% for message in messages %}
				<div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				  </button>
				  {{ message }}
				</div>
				{% endfor %}
			  {% endif %}
			{% endwith %}
			<form action="#" method = "post">
				<div class="form-group">
					<label for="style">Name:</label>
					<input type ="text" maxlength="100" class="form-control" name="style" value="">
					<label for="description">Description:</label>
					<textarea class="form-control" maxlength="250" rows="3" name="description"></textarea>
				</div>
				<br>
				<button type="submit" class="btn btn-info" id="submit" type="submit">
				<span aria-hidden="true"></span>Save</button>
				<a class= "btn btn-default" href = "{{url_for('category.show_categories')}}">Cancel</a>
			</form>
		</div>
	</div>
</div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" 
    integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
      crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" 
    integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
      crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" 
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='main.css') }}">

    <title>
      <h1>Catalog App</h1>
    </title>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{url_for('category.show_categories')}}"><h3>Catalog App</h3></a>
        </div>
        <ul class="nav navbar">
          <li class= "nav-item"><a href="{{url_for('category.show_categories')}}">Categories</a></li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            {% if 'username' not in session %}
              <a href="{{url_for('auth.show_login')}}"><span class="fas fa-sign-in-alt"></span>SignIn</a>
            {% else %}
              <a href="#" data-toggle="popover" data-trigger="focus" 
                title="Authentication" 
                data-content="{{ session['username'] }} ({{ session['email'] }})">
              </a>
              <a href="{{url_for('auth.disconnect')}}"><span class="fas fa-sign-out-alt"></span>SignOut</a>
            {% endif %}
          </form>
      </div>
    </nav>

    <div class= "jumbotron">
      <h2 class= "jumbo-content">Winter Catalog</h2>
    </div>
    
    <div class="container-fluid" style="margin-top: 1rem;">
      <!-- Content here -->
      {% block content %}{% endblock %}
    </div>
    </body>
    
    <footer class = "container">

    </footer>

    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>

    <script>
      // Get the current year for the copyright
      $('#year').text(new Date().getFullYear());
      $(function() {
        $('[data-toggle="popover"]').popover()
      });
    </script>
  </body>
</html>

app/templates/item_detail.html
{% include 'partials/navbar.html' %}
{% block content %}

<section class = 'item-info'>
    <div>
        <h1 class = 'cat-head'>
            {{item.style}}
        </h1>
    </div>
    <div>
        <p class = 'item-desc'>{{item.description}}</p>
    </div>
    <div>
        <a class = "btn btn-info" href="{{url_for('item.edit_item', category_name = category.name, item_style = item.style)}}">Edit</a>
        <a class = "btn btn-info" href="{{url_for('item.delete_item', category_name = category.name, item_style = item.style)}}">Delete</a>
    </div>
</section>

{% endblock %}

app/templates/login.html
<html>
    <head>
        {% include "partials/navbar.html" %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script src="//apis.google.com/js/platform.js?onload=start"> </script>
    </head> 
    <body class= "login">
        <section class= "login-page">
            <div class= "login-box">
                <h1>User Login</h1>
                <p>Please login using the following options:</p>
            </div>
            <button class= "fb-login">
                    <fb:login-button scope="public_profile,email" onlogin="sendTokenToServer();">
                      <a href='javascript:sendTokenToServer()'>Login with Facebook</a>
                    </fb:login-button>
            </button>
            <div id="signInButton">
                <span class="g-signin" 
                        data-scope="openid email"
                        data-clientid="759360808940-631pr3lc5o998p8r8rkrb5gujt5gjm9n.apps.googleusercontent.com"
                        data-redirecturi="postmessage"
                        data-accesstype="offline"
                        data-cookiepolicy="single_host_origin"
                        data-callback="signInCallback"
                        data-approvalprompt="force">
                </span>
            </div>
                
            <div id="result"></div>
        
            
            <script>
            function signInCallback(authResult) {
                if (authResult["code"]) {
                // Hide the sign-in button now that the user is authorized
                $("#signinButton").attr("style", "display: none");
                // Send the one-time-use code to the server, if the server responds, 
                // write a "login successful" message to the web page and then redirect 
                // back to the main catalog page
                $.ajax({
                    type: "POST",
                    url: "/gconnect?state={{STATE}}",
                    processData: false,
                    data: authResult["code"],
                    contentType: "application/octet-stream; charset=utf-8",
                    success: function(result) {
                    // Handle or verify the server response if necessary.
                    if (result) {
                        $("#result").html("Login Successful!<br>" + result + "<br>Redirecting...");
                        setTimeout(function() {
                        window.location.href = "/catalog";
                        }, 4000);
                    } else if (authResult["error"]) {
                        console.log("There was an error: " + authResult["error"]);
                    } else {
                        $("#result").html("Failed to make a server-side call. Check your configuration and console.");
                    }
                    }  
                }); 
                }
            }
            </script>

<script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '805060193179471',
            cookie     : true,  // enable cookies to allow the server to access 
                                // the session
            xfbml      : true,  // parse social plugins on this page
            version    : 'v3.2' // use version 2.2
          });
        };
        // Load the SDK asynchronously
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        
        // Here we run a very simple test of the Graph API after login is
        // successful.  See statusChangeCallback() for when this call is made.
        function sendTokenToServer() {
          var access_token = FB.getAuthResponse()['accessToken'];
          console.log(access_token)
          console.log('Welcome!  Fetching your information.... ');
          FB.api('/me', function(response) {
            console.log('Successful login for: ' + response.name);
            $.ajax({
              type: 'POST',
              url: '/fbconnect?state={{STATE}}',
              processData: false,
              data: access_token,
              contentType: 'application/octet-stream; charset=utf-8',
              success: function(result) {
                // Handle or verify the server response if necessary.
                if (result) {
                  $('#result').html('Login Successful!</br>'+ result + '</br>Redirecting...')
                  setTimeout(function() {
                    window.location.href = "/catalog";
                  }, 4000);
                } else {
                  $('#result').html('Failed to make a server-side call. Check your configuration and console.');
                }
              }   
            });
          });
        }
      </script>
      
      <!--END FACEBOOK SIGN IN -->
    </body>
</html>

app/templates/new_item.html
{% block content %}
{% include "partials/navbar.html" %}

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2>Create New Item</h2>
			{% with messages = get_flashed_messages() %}
			{% if messages %}
			  {% for message in messages %}
				<div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				  </button>
				  {{ message }}
				</div>
			  {% endfor %}
			{% endif %}
		  {% endwith %}
			<form action="#" method = "post">
				<div class="form-group">
					<label for="style">Name:</label>
					<input type ="text" maxlength="100" class="form-control" name="style" value="">
					<label for="description">Description:</label>
					<textarea class="form-control" maxlength="250" rows="3" name="description"></textarea>
					</div>
					<br>
					<button type="submit" class="btn btn-info" id="submit" type="submit">
					<span  aria-hidden="true"></span>Save</button>
					<a  class= "btn btn-default" href = "{{url_for('category.show_categories')}}">Cancel</a>
			</form>
		</div>		
	</div>
</div>

{% endblock %}

app/templates/show_item.html
{% extends "index.html" %}
{% block content %} 

<section class="container">
        <h3 class = 'cat-head'>{{category.name}}</h3>
        {% with messages = get_flashed_messages() %}
			{% if messages %}
			  {% for message in messages %}
				<div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 1rem;">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				  </button>
				  {{ message }}
				</div>
				{% endfor %}
			  {% endif %}
			{% endwith %}
            <div class="row">
                {% for i in items %}
                    <button class="col-sm-4">
                      <a class= cat-link href ="{{url_for('item.show_item', category_name=i.category.name, item_style=i.style)}}">{{i.style}}</a>
                    </button>
                {% endfor %}
            </div>
        <span>
            <a href="{{url_for('item.new_item', category_name = category.name)}}" class="btn btn-info" role="button">Add New Item</a>
        </span>
</section> 
{% endblock %}